/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Food: typeof import('./components/category/Food.vue')['default']
    Fresh: typeof import('./components/category/Fresh.vue')['default']
    GoodsPanel: typeof import('./components/category/GoodsPanel.vue')['default']
    HomeBannerCategory: typeof import('./components/Home/HomeBannerCategory.vue')['default']
    HomeCart: typeof import('./components/Home/HomeCart.vue')['default']
    HomeFresh: typeof import('./components/Home/HomeFresh.vue')['default']
    HomeGoods: typeof import('./components/Home/HomeGoods.vue')['default']
    HomeHot: typeof import('./components/Home/HomeHot.vue')['default']
    HomeNew: typeof import('./components/Home/HomeNew.vue')['default']
    HomeOrder: typeof import('./components/Home/HomeOrder.vue')['default']
    HomePanel: typeof import('./components/Home/HomePanel.vue')['default']
    Homepay: typeof import('./components/Home/Homepay.vue')['default']
    HomePayQrcode: typeof import('./components/Home/HomePayQrcode.vue')['default']
    HomeRenqi: typeof import('./components/Home/HomeRenqi.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
