/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Food: typeof import('./components/category/Food.vue')['default']
    Fresh: typeof import('./components/category/Fresh.vue')['default']
    GoodsPanel: typeof import('./components/category/GoodsPanel.vue')['default']
    HomeBannerCategory: typeof import('./components/Home/HomeBannerCategory.vue')['default']
    HomeCart: typeof import('./components/Home/HomeCart.vue')['default']
    HomeFresh: typeof import('./components/Home/HomeFresh.vue')['default']
    HomeGoods: typeof import('./components/Home/HomeGoods.vue')['default']
    HomeHot: typeof import('./components/Home/HomeHot.vue')['default']
    HomeNew: typeof import('./components/Home/HomeNew.vue')['default']
    HomePanel: typeof import('./components/Home/HomePanel.vue')['default']
    HomeRenqi: typeof import('./components/Home/HomeRenqi.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
